var butterflies =[
    // Rarity: The closer to 1, the more common.
    {id: 1,
    name: "Cabbage Butterfly",
    desc: "These are a very common butterfly.",
    rarity: .7,
    prize: 5,
    special: false,
    quant: 0,
    image: "cabbage",
    spawnswith: [1,2,3,4,5],
    flavour: `Hey, cutie!`
    },
    {id: 2,
    name: "Fiery Skipper",
    desc: "Fiery Skippers fly fast and are very fuzzy.",
    rarity: .5,
    prize: 10,
    special: false,
    quant: 0,
    image: "fireskipper",
    spawnswith: [3,4,5],
    flavour: `Ooh, fuzzy!`
    },
    {id: 3,
    name: "Honey Bee",
    desc: "Not a butterfly, but a friend nonetheless.",
    rarity: .1,
    prize: 20,
    special: false,
    quant: 0,
    image: "honeybee",
    spawnswith: [4,5,6,7],
    flavour: `Oh my!`
    },
    {id: 4,
    name: "Sweat Bee",
    desc: "...To be honest, these lil fellas show up quite a bit.",
    rarity: .5,
    prize: 5,
    special: false,
    quant: 0,
    image: "sweatbee",
    spawnswith: [1,2,3,4,5],
    flavour: `Phooey.`
    },
    {id: 5,
    name: "Mud Dauber",
    desc: "Eek! This is a wasp.",
    rarity: .05,
    prize: 35,
    special: false,
    quant: 0,
    image: "wasp",
    spawnswith: [1,2,3,4,5],
    flavour: `Eeek!!`
    },
    {id: 5,
    name: "Tiger Swallowtail",
    desc: "A beautiful butterfly with stripes and splashes of blue.",
    rarity: .15,
    prize: 45,
    special: false,
    quant: 0,
    image: "tiger",
    spawnswith: [6,7],
    flavour: `Oh, pretty!`
    },
]
